
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Terminal.Gui {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainGUI : Terminal.Gui.Window {
        
        private Terminal.Gui.View animalsBoard;
        
        private void InitializeComponent() {
            this.animalsBoard = new Terminal.Gui.View();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.animalsBoard.Width = Dim.Fill(0);
            this.animalsBoard.Height = Dim.Percent(40f);
            this.animalsBoard.X = 0;
            this.animalsBoard.Y = 17;
            this.animalsBoard.Visible = true;
            this.animalsBoard.Data = "animalsBoard";
            this.animalsBoard.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.animalsBoard);
        }
    }
}
